const chartTypeDispatch = {
  '100%-stacked-bar': ['renderCartesian', '100%-stacked-bar'],
  '100%-stacked-column': ['renderCartesian', '100%-stacked-column'],
  '3d-surface': ['renderContour', 'contour'],
  alluvial: ['renderSankey', 'alluvial'],
  'arc-diagram': ['renderNetwork', 'network'],
  area: ['renderCartesian', 'area'],
  'aging-bucket': ['renderEnterprise'],
  bar: ['renderCartesian', 'bar'],
  'barcode-chart': ['renderHeatmap'],
  beeswarm: ['renderScatter', 'scatter'],
  'boxen-plot': ['renderEnterprise'],
  boxplot: ['renderBoxplot', 'boxplot'],
  bubble: ['renderScatter', 'bubble'],
  'bubble-map': ['renderMap', 'symbol-map'],
  bullet: ['renderBullet'],
  burndown: ['renderEnterprise'],
  burnup: ['renderEnterprise'],
  bump: ['renderSlope', 'bump'],
  'calendar-event': ['renderCalendarEvents'],
  'calendar-heatmap': ['renderHeatmap'],
  candlestick: ['renderCandlestick'],
  cartogram: ['renderMap', 'choropleth'],
  chord: ['renderChord'],
  choropleth: ['renderMap', 'choropleth'],
  column: ['renderCartesian', 'column'],
  combo: ['renderCartesian', 'combo'],
  'confidence-band': ['renderCartesian', 'confidence-band'],
  contour: ['renderContour', 'contour'],
  'control-chart': ['renderControlChart'],
  'cohort-funnel': ['renderEnterprise'],
  'cohort-retention': ['renderEnterprise'],
  'correlation-matrix': ['renderEnterprise'],
  'cumulative-flow': ['renderEnterprise'],
  'dependency-graph': ['renderNetwork', 'dependency-graph'],
  'decomposition-tree': ['renderEnterprise'],
  density: ['renderContour', 'density'],
  donut: ['renderRadial', 'donut'],
  'dot-plot': ['renderScatter', 'scatter'],
  dumbbell: ['renderSlope', 'slope'],
  'edge-bundling': ['renderNetwork', 'network'],
  'error-band': ['renderCartesian', 'error-band'],
  'error-bar': ['renderCartesian', 'error-bar'],
  'flow-map': ['renderMap', 'flow-map'],
  'floating-bar': ['renderCartesian', 'floating-bar'],
  'force-directed': ['renderNetwork', 'force-directed'],
  'forecast-fan': ['renderEnterprise'],
  funnel: ['renderFunnel', 'funnel'],
  gantt: ['renderGantt'],
  gauge: ['renderGauge', 'gauge'],
  'geo-heatmap': ['renderMap', 'geo-heatmap'],
  'grouped-bar': ['renderCartesian', 'grouped-bar'],
  'grouped-column': ['renderCartesian', 'grouped-column'],
  'heikin-ashi': ['renderCandlestick'],
  heatmap: ['renderHeatmap'],
  hexbin: ['renderHexbin'],
  histogram: ['renderCartesian', 'histogram'],
  icicle: ['renderTree', 'icicle'],
  'journey-map': ['renderGantt'],
  kagi: ['renderCandlestick'],
  kpi: ['renderGauge', 'kpi'],
  line: ['renderCartesian', 'line'],
  'liquid-fill': ['renderGauge', 'gauge'],
  lollipop: ['renderCartesian', 'bar'],
  marimekko: ['renderMarimekko'],
  'map-with-clusters': ['renderMap', 'symbol-map'],
  'map-with-markers': ['renderMap', 'symbol-map'],
  'market-depth': ['renderCartesian', 'area'],
  meter: ['renderGauge', 'meter'],
  mesh: ['renderContour', 'contour'],
  milestone: ['renderTimelineEvents'],
  'mind-map': ['renderTree', 'mind-map'],
  'multi-line': ['renderCartesian', 'line'],
  'matrix-network': ['renderNetwork', 'network'],
  mosaic: ['renderMarimekko'],
  network: ['renderNetwork', 'network'],
  'network-graph': ['renderNetwork', 'network-graph'],
  'nested-donut': ['renderRadial', 'donut'],
  ohlc: ['renderCandlestick'],
  'org-chart': ['renderTree', 'org-chart'],
  'parallel-coordinates': ['renderParallelCoordinates'],
  pareto: ['renderCartesian', 'combo'],
  pie: ['renderRadial', 'pie'],
  pictogram: ['renderWaffle'],
  'point-and-figure': ['renderCandlestick'],
  'polar-area': ['renderRadial', 'polar-area'],
  'probability-plot': ['renderScatter', 'scatter'],
  'process-flow': ['renderSankey', 'sankey'],
  'progress-ring': ['renderRadial', 'radial-bar'],
  pyramid: ['renderFunnel', 'pyramid'],
  'qq-plot': ['renderScatter', 'scatter'],
  radar: ['renderRadar'],
  'radial-bar': ['renderRadial', 'radial-bar'],
  'range-area': ['renderCartesian', 'range-area'],
  'range-bar': ['renderCartesian', 'range-bar'],
  'range-column': ['renderCartesian', 'range-column'],
  renko: ['renderCandlestick'],
  'resource-utilization': ['renderEnterprise'],
  'risk-matrix': ['renderEnterprise'],
  ridgeline: ['renderContour', 'density'],
  rose: ['renderRadial', 'rose'],
  'route-map': ['renderMap', 'flow-map'],
  sankey: ['renderSankey', 'sankey'],
  scatter: ['renderScatter', 'scatter'],
  'semi-donut': ['renderRadial', 'donut'],
  slope: ['renderSlope', 'slope'],
  'small-multiples': ['renderEnterprise'],
  'slo-error-budget-burn': ['renderEnterprise'],
  sparkline: ['renderSparkline'],
  spectrogram: ['renderHeatmap'],
  spider: ['renderRadar'],
  'stacked-100-area': ['renderCartesian', 'stacked-100-area'],
  'stacked-area': ['renderCartesian', 'stacked-area'],
  'stacked-bar': ['renderCartesian', 'stacked-bar'],
  'stacked-column': ['renderCartesian', 'stacked-column'],
  'status-timeline': ['renderTimelineEvents'],
  'step-line': ['renderCartesian', 'line'],
  'strip-plot': ['renderScatter', 'scatter'],
  streamgraph: ['renderStreamgraph'],
  surface: ['renderContour', 'contour'],
  sunburst: ['renderTreemap'],
  'symbol-map': ['renderMap', 'symbol-map'],
  ternary: ['renderScatter', 'scatter'],
  tornado: ['renderEnterprise'],
  'tile-map': ['renderMap', 'choropleth'],
  'timeline-event': ['renderTimelineEvents'],
  'timeline-range': ['renderGantt'],
  treemap: ['renderTreemap'],
  'tree-diagram': ['renderTree', 'tree-diagram'],
  'unit-chart': ['renderWaffle'],
  'vector-field': ['renderScatter', 'scatter'],
  violin: ['renderBoxplot', 'violin'],
  'variance-budget-actual': ['renderEnterprise'],
  waffle: ['renderWaffle'],
  waterfall: ['renderCartesian', 'waterfall'],
  'word-cloud': ['renderTreemap'],
  'word-tree': ['renderTree', 'tree-diagram'],
  'volume-candlestick': ['renderCandlestick']
};

export function getChartDispatch(type) {
  return chartTypeDispatch[type] || chartTypeDispatch.line;
}

export const chartTypes = Object.freeze(Object.keys(chartTypeDispatch));
