export {};

export * from './core.js';
export { MvxButton } from './components/button/index.js';
export { MvxIconButton } from './components/icon-button/index.js';
export { MvxCard } from './components/card/index.js';
export { MvxBadge } from './components/badge/index.js';
export { MvxAlert } from './components/alert/index.js';
export { MvxSwitch } from './components/switch/index.js';
export { MvxInput } from './components/input/index.js';
export { MvxCheckbox } from './components/checkbox/index.js';
export { MvxRadioGroup } from './components/radio-group/index.js';
export { MvxSelect } from './components/select/index.js';
export { MvxTextarea } from './components/textarea/index.js';
export { MvxSlider } from './components/slider/index.js';
export { MvxDatePicker } from './components/date-picker/index.js';
export { MvxModal } from './components/modal/index.js';
export { MvxDrawer } from './components/drawer/index.js';
export { MvxToast } from './components/toast/index.js';
export { MvxAppShell } from './components/app-shell/index.js';
export { MvxDataTable } from './components/data-table/index.js';
export { MvxChart } from './components/chart/index.js';
export { MvxChartGroup } from './components/chart-group/index.js';
export { MvxCommandPalette } from './components/command-palette/index.js';
export { MvxAssistantPanel } from './components/ai-panel/index.js';
export { MvxChatbot } from './components/chatbot/index.js';
export { MvxKanban } from './components/kanban/index.js';
export { MvxAccordion } from './components/accordion/index.js';
export { MvxTabs } from './components/tabs/index.js';
export { MvxBreadcrumbs } from './components/breadcrumbs/index.js';
export { MvxPagination } from './components/pagination/index.js';
export { MvxProgress } from './components/progress/index.js';
export { MvxSkeleton } from './components/skeleton/index.js';
export { MvxAvatar } from './components/avatar/index.js';
export { MvxTooltip } from './components/tooltip/index.js';
export { MvxTimeline } from './components/timeline/index.js';
export { MvxThemeSwitcher } from './components/theme-switcher/index.js';
export { MvxDropdownMenu } from './components/dropdown-menu/index.js';
export { MvxPopover } from './components/popover/index.js';
export { MvxNavbar } from './components/navbar/index.js';
export { MvxSidebar } from './components/sidebar/index.js';
export { MvxDivider } from './components/divider/index.js';
export { MvxList } from './components/list/index.js';
export { MvxSpinner } from './components/spinner/index.js';
export { MvxStepper } from './components/stepper/index.js';
export { MvxShortcuts } from './components/shortcuts/index.js';
export * from './components/peer-parity.js';

declare global {
  namespace JSX {
    interface MivixGlobalAttributes {
      theme?: 'dark' | 'light' | 'graphite' | 'aurora' | 'terminal' | string;
      componentStyle?: 'console' | 'minimal' | 'glass' | 'dashboard' | string;
      'component-style'?: 'console' | 'minimal' | 'glass' | 'dashboard' | string;
      font?: 'system' | 'inter' | 'mono' | 'monospace' | 'serif' | 'rounded' | 'humanist' | 'geometric' | 'devanagari' | string;
      fontFamily?: string;
      'font-family'?: string;
      radius?: number | string;
      dir?: 'ltr' | 'rtl' | 'auto';
      lang?: string;
      locale?: string;
      skeleton?: boolean | 'text' | 'card' | 'chart' | 'table' | 'avatar' | 'button' | 'input' | string;
      skeletonLines?: number | string;
      'skeleton-lines'?: number | string;
      i18n?: string | Record<string, string>;
    }

    interface IntrinsicElements {
      'mvx-button': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-icon-button': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-card': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-badge': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-alert': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-switch': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-input': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-checkbox': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-radio-group': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-select': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-textarea': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-slider': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-date-picker': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-modal': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-drawer': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-toast': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-app-shell': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-data-table': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-chart': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-chart-group': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-command-palette': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-ai-panel': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-chatbot': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-kanban': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-accordion': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-tabs': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-breadcrumbs': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-pagination': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-progress': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-skeleton': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-avatar': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-tooltip': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-timeline': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-theme-switcher': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-dropdown-menu': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-popover': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-navbar': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-sidebar': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-divider': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-list': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-spinner': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-stepper': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-shortcuts': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-alert-dialog': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-aspect-ratio': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-attachment': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-autocomplete': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-aura': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-backdrop': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-bottom-navigation': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-box': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-browser-mockup': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-bubble': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-button-group': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-calendar': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-carousel': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-chat-bubble': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-chip': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-close-button': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-code-block': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-collapse': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-combobox': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-container': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-context-menu': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-countdown': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-dialog': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-diff': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-dock': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-empty-state': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-fab': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-field': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-fieldset': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-figure': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-file-input': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-filter': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-floating-label': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-footer': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-grid': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-hero': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-hover-3d-card': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-hover-card': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-hover-gallery': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-icon': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-icons': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-image': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-image-list': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-indicator': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-input-group': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-item': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-join': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-json-renderer': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-json-schema-form': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-kbd': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-label': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-link': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-masonry': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-marker': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-mask': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-mega-menu': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-menu': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-menubar': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-message': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-message-scroller': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-native-select': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-navigation-menu': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-number-field': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-offcanvas': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-otp-input': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-paper': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-placeholder': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-phone-mockup': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-radial-progress': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-rating': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-resizable': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-rich-text-editor': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-scroll-area': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-scrollspy': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-schema-form': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-separator': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-sheet': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-sonner': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-speed-dial': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-stack': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-stat': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-status': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-swap': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-table': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-text-rotate': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-theme-controller': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-toggle': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-toggle-group': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-transfer-list': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-tree-view': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-typography': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-validator': MivixGlobalAttributes & Record<string, unknown>;
      'mvx-window-mockup': MivixGlobalAttributes & Record<string, unknown>;
    }
  }
}
